name: Deploy Lambda
on:
  push:
    branches: [ main ]

# Add this permissions block
permissions:
  id-token: write    # Required for OIDC
  contents: read     # Required to checkout repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228662049252:role/githubActions
          aws-region: us-east-1

      - name: Zip Function
        run: |
          zip -j function.zip ./lambda_function.py  # Or your function file

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name github-actions \
            --zip-file fileb://function.zip
